#!/bin/env bash
podman pull ubuntu:24.04
podman run -d --mount=type=bind,src=./script,destination=/root/customize_file --name=kernel_customize ubuntu:24.04  tail -f /dev/null
podman exec --privileged kernel_customize /root/customize_file/build_kernel_ubuntu
podman cp kernel_customize:/root/kernel_customize/arch/x86/boot/bzImage ./bzImage
podman stop kernel_customize
podman container rm kernel_customize
